cabal-version:       2.2

name:                aoc2015
version:             0.1.0.0
-- synopsis:
-- description:
homepage:            https://github.com/githubuser/aoc2015#readme
license:             BSD-3-Clause
license-file:        LICENSE
author:              Author name here
maintainer:          example@example.com
copyright:           2026 Author name here
category:            Web
build-type:          Simple
extra-source-files:  README.md
                     CHANGELOG.md

executable aoc2015
  hs-source-dirs:      src
  main-is:             Main.hs
  other-modules:       Day01
                     , Day02
                     , Day03
  default-language:    Haskell2010
  build-depends:       base >= 4.7 && < 5
                     , containers
                     , split
                     , transformers
  ghc-options:         -Wall
                       -Wcompat
                       -Wincomplete-uni-patterns

source-repository head
  type:     git
  location: https://github.com/githubuser/aoc2015
